<?php
/**
 * AdminPromotions200GetCouponPromotionModel
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shop Builder API
 *
 * # Overview  * **Version:** 2.0.0 * **Servers**: `https://store.xsolla.com/api` * **[Contact Us by Email](mailto:integration@xsolla.com)** * **Contact URL:** https://xsolla.com/ * **Required TLS version:** 1.2  Shop Builder API provides a third-party solution for implementing the server side for your store interface. Use the endpoints to manage in-game items, in-game currencies, cart, player inventory, promotions, game library, etc.  # Download API definition  You can download the API definition in two formats: - [YAML](https://api.redocly.com/registry/bundle/xsolla/store-en/v1/openapi.yaml) - [JSON](https://api.redocly.com/registry/bundle/xsolla/store-en/v1/openapi.json)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AdminPromotions200GetCouponPromotionModel Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AdminPromotions200GetCouponPromotionModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'admin-promotions_200-get-coupon-promotion-model';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'external_id' => 'string',
        'date_start' => '\DateTime',
        'date_end' => '\DateTime',
        'name' => 'array<string,string>',
        'bonus' => '\OpenAPI\Client\Model\CreateBonusPromotionRequestBonusInner[]',
        'is_enabled' => 'bool',
        'redeem_total_limit' => 'int',
        'redeem_user_limit' => 'int',
        'redeem_code_limit' => 'int',
        'total_limit_state' => '\OpenAPI\Client\Model\PromotionsCouponTotalLimitState',
        'attribute_conditions' => '\OpenAPI\Client\Model\AdminPromotions200GetCouponPromotionModelAttributeConditions'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'external_id' => null,
        'date_start' => 'date-time',
        'date_end' => 'date-time',
        'name' => null,
        'bonus' => null,
        'is_enabled' => null,
        'redeem_total_limit' => null,
        'redeem_user_limit' => null,
        'redeem_code_limit' => null,
        'total_limit_state' => null,
        'attribute_conditions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'external_id' => false,
        'date_start' => true,
        'date_end' => true,
        'name' => false,
        'bonus' => true,
        'is_enabled' => false,
        'redeem_total_limit' => true,
        'redeem_user_limit' => true,
        'redeem_code_limit' => true,
        'total_limit_state' => true,
        'attribute_conditions' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'external_id' => 'external_id',
        'date_start' => 'date_start',
        'date_end' => 'date_end',
        'name' => 'name',
        'bonus' => 'bonus',
        'is_enabled' => 'is_enabled',
        'redeem_total_limit' => 'redeem_total_limit',
        'redeem_user_limit' => 'redeem_user_limit',
        'redeem_code_limit' => 'redeem_code_limit',
        'total_limit_state' => 'total_limit_state',
        'attribute_conditions' => 'attribute_conditions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'external_id' => 'setExternalId',
        'date_start' => 'setDateStart',
        'date_end' => 'setDateEnd',
        'name' => 'setName',
        'bonus' => 'setBonus',
        'is_enabled' => 'setIsEnabled',
        'redeem_total_limit' => 'setRedeemTotalLimit',
        'redeem_user_limit' => 'setRedeemUserLimit',
        'redeem_code_limit' => 'setRedeemCodeLimit',
        'total_limit_state' => 'setTotalLimitState',
        'attribute_conditions' => 'setAttributeConditions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'external_id' => 'getExternalId',
        'date_start' => 'getDateStart',
        'date_end' => 'getDateEnd',
        'name' => 'getName',
        'bonus' => 'getBonus',
        'is_enabled' => 'getIsEnabled',
        'redeem_total_limit' => 'getRedeemTotalLimit',
        'redeem_user_limit' => 'getRedeemUserLimit',
        'redeem_code_limit' => 'getRedeemCodeLimit',
        'total_limit_state' => 'getTotalLimitState',
        'attribute_conditions' => 'getAttributeConditions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('external_id', $data ?? [], 'coupon_external_id');
        $this->setIfExists('date_start', $data ?? [], null);
        $this->setIfExists('date_end', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('bonus', $data ?? [], null);
        $this->setIfExists('is_enabled', $data ?? [], true);
        $this->setIfExists('redeem_total_limit', $data ?? [], 10);
        $this->setIfExists('redeem_user_limit', $data ?? [], 10);
        $this->setIfExists('redeem_code_limit', $data ?? [], 10);
        $this->setIfExists('total_limit_state', $data ?? [], null);
        $this->setIfExists('attribute_conditions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id Unique promotion ID. The `external_id` may contain only lowercase and uppercase Latin alphanumeric characters, periods, dashes, and underscores.
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        if (is_null($external_id)) {
            throw new \InvalidArgumentException('non-nullable external_id cannot be null');
        }
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets date_start
     *
     * @return \DateTime|null
     */
    public function getDateStart()
    {
        return $this->container['date_start'];
    }

    /**
     * Sets date_start
     *
     * @param \DateTime|null $date_start Date when your promotion will be started.
     *
     * @return self
     */
    public function setDateStart($date_start)
    {
        if (is_null($date_start)) {
            array_push($this->openAPINullablesSetToNull, 'date_start');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_start', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_start'] = $date_start;

        return $this;
    }

    /**
     * Gets date_end
     *
     * @return \DateTime|null
     */
    public function getDateEnd()
    {
        return $this->container['date_end'];
    }

    /**
     * Sets date_end
     *
     * @param \DateTime|null $date_end Date when your promotion will be finished. Can be `null`.  If `date_end` is `null`, promotion will be unlimited by time.
     *
     * @return self
     */
    public function setDateEnd($date_end)
    {
        if (is_null($date_end)) {
            array_push($this->openAPINullablesSetToNull, 'date_end');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_end', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_end'] = $date_end;

        return $this;
    }

    /**
     * Gets name
     *
     * @return array<string,string>|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param array<string,string>|null $name Name of promotion. Should contain key/value pairs where key is a locale with \"^[a-z]{2}-[A-Z]{2}$\" format, value is string.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets bonus
     *
     * @return \OpenAPI\Client\Model\CreateBonusPromotionRequestBonusInner[]|null
     */
    public function getBonus()
    {
        return $this->container['bonus'];
    }

    /**
     * Sets bonus
     *
     * @param \OpenAPI\Client\Model\CreateBonusPromotionRequestBonusInner[]|null $bonus bonus
     *
     * @return self
     */
    public function setBonus($bonus)
    {
        if (is_null($bonus)) {
            array_push($this->openAPINullablesSetToNull, 'bonus');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bonus', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bonus'] = $bonus;

        return $this;
    }

    /**
     * Gets is_enabled
     *
     * @return bool|null
     */
    public function getIsEnabled()
    {
        return $this->container['is_enabled'];
    }

    /**
     * Sets is_enabled
     *
     * @param bool|null $is_enabled is_enabled
     *
     * @return self
     */
    public function setIsEnabled($is_enabled)
    {
        if (is_null($is_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_enabled cannot be null');
        }
        $this->container['is_enabled'] = $is_enabled;

        return $this;
    }

    /**
     * Gets redeem_total_limit
     *
     * @return int|null
     */
    public function getRedeemTotalLimit()
    {
        return $this->container['redeem_total_limit'];
    }

    /**
     * Sets redeem_total_limit
     *
     * @param int|null $redeem_total_limit Limits total numbers of coupons.
     *
     * @return self
     */
    public function setRedeemTotalLimit($redeem_total_limit)
    {
        if (is_null($redeem_total_limit)) {
            array_push($this->openAPINullablesSetToNull, 'redeem_total_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redeem_total_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redeem_total_limit'] = $redeem_total_limit;

        return $this;
    }

    /**
     * Gets redeem_user_limit
     *
     * @return int|null
     */
    public function getRedeemUserLimit()
    {
        return $this->container['redeem_user_limit'];
    }

    /**
     * Sets redeem_user_limit
     *
     * @param int|null $redeem_user_limit Limits total numbers of coupons redeemed by single user.
     *
     * @return self
     */
    public function setRedeemUserLimit($redeem_user_limit)
    {
        if (is_null($redeem_user_limit)) {
            array_push($this->openAPINullablesSetToNull, 'redeem_user_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redeem_user_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redeem_user_limit'] = $redeem_user_limit;

        return $this;
    }

    /**
     * Gets redeem_code_limit
     *
     * @return int|null
     */
    public function getRedeemCodeLimit()
    {
        return $this->container['redeem_code_limit'];
    }

    /**
     * Sets redeem_code_limit
     *
     * @param int|null $redeem_code_limit Number of redemptions per code.
     *
     * @return self
     */
    public function setRedeemCodeLimit($redeem_code_limit)
    {
        if (is_null($redeem_code_limit)) {
            array_push($this->openAPINullablesSetToNull, 'redeem_code_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redeem_code_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redeem_code_limit'] = $redeem_code_limit;

        return $this;
    }

    /**
     * Gets total_limit_state
     *
     * @return \OpenAPI\Client\Model\PromotionsCouponTotalLimitState|null
     */
    public function getTotalLimitState()
    {
        return $this->container['total_limit_state'];
    }

    /**
     * Sets total_limit_state
     *
     * @param \OpenAPI\Client\Model\PromotionsCouponTotalLimitState|null $total_limit_state total_limit_state
     *
     * @return self
     */
    public function setTotalLimitState($total_limit_state)
    {
        if (is_null($total_limit_state)) {
            array_push($this->openAPINullablesSetToNull, 'total_limit_state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_limit_state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_limit_state'] = $total_limit_state;

        return $this;
    }

    /**
     * Gets attribute_conditions
     *
     * @return \OpenAPI\Client\Model\AdminPromotions200GetCouponPromotionModelAttributeConditions|null
     */
    public function getAttributeConditions()
    {
        return $this->container['attribute_conditions'];
    }

    /**
     * Sets attribute_conditions
     *
     * @param \OpenAPI\Client\Model\AdminPromotions200GetCouponPromotionModelAttributeConditions|null $attribute_conditions attribute_conditions
     *
     * @return self
     */
    public function setAttributeConditions($attribute_conditions)
    {
        if (is_null($attribute_conditions)) {
            throw new \InvalidArgumentException('non-nullable attribute_conditions cannot be null');
        }
        $this->container['attribute_conditions'] = $attribute_conditions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


