<?php
/**
 * BundlesAdminBundleResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shop Builder API
 *
 * # Overview  * **Version:** 2.0.0 * **Servers**: `https://store.xsolla.com/api` * **[Contact Us by Email](mailto:integration@xsolla.com)** * **Contact URL:** https://xsolla.com/ * **Required TLS version:** 1.2  Shop Builder API provides a third-party solution for implementing the server side for your store interface. Use the endpoints to manage in-game items, in-game currencies, cart, player inventory, promotions, game library, etc.  # Download API definition  You can download the API definition in two formats: - [YAML](https://api.redocly.com/registry/bundle/xsolla/store-en/v1/openapi.yaml) - [JSON](https://api.redocly.com/registry/bundle/xsolla/store-en/v1/openapi.json)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BundlesAdminBundleResponse Class Doc Comment
 *
 * @category Class
 * @description The specified bundle.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BundlesAdminBundleResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Bundles_admin_bundle_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'item_id' => 'int',
        'sku' => 'string',
        'name' => '\OpenAPI\Client\Model\NameLocalizationObject',
        'attributes' => '\OpenAPI\Client\Model\Attribute[]',
        'type' => 'string',
        'bundle_type' => '\OpenAPI\Client\Model\BundleType',
        'description' => '\OpenAPI\Client\Model\DescriptionLocalizationObject',
        'long_description' => '\OpenAPI\Client\Model\LongDescriptionLocalizationObject',
        'image_url' => 'string',
        'is_free' => 'bool',
        'groups' => '\OpenAPI\Client\Model\BundlesGroupsResponseInner[]',
        'prices' => '\OpenAPI\Client\Model\BundlesPricesInner[]',
        'virtual_prices' => '\OpenAPI\Client\Model\BundlesAdminResponseVirtualPrice[]',
        'media_list' => 'ArrayString',
        'order' => 'int',
        'is_enabled' => 'bool',
        'is_show_in_store' => 'bool',
        'regions' => '\OpenAPI\Client\Model\BundlesAdminRegionsInner[]',
        'content' => '\OpenAPI\Client\Model\BundlesAdminContentResponse[]',
        'limits' => '\OpenAPI\Client\Model\ItemLimitResponse',
        'periods' => '\OpenAPI\Client\Model\ItemPeriodsResponseInner[]',
        'custom_attributes' => 'object',
        'total_content_price' => '\OpenAPI\Client\Model\BundlesTotalContentPrice'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'item_id' => null,
        'sku' => null,
        'name' => null,
        'attributes' => null,
        'type' => null,
        'bundle_type' => null,
        'description' => null,
        'long_description' => null,
        'image_url' => null,
        'is_free' => null,
        'groups' => null,
        'prices' => null,
        'virtual_prices' => null,
        'media_list' => null,
        'order' => null,
        'is_enabled' => null,
        'is_show_in_store' => null,
        'regions' => null,
        'content' => null,
        'limits' => null,
        'periods' => null,
        'custom_attributes' => 'json',
        'total_content_price' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'item_id' => false,
        'sku' => false,
        'name' => true,
        'attributes' => false,
        'type' => false,
        'bundle_type' => false,
        'description' => true,
        'long_description' => true,
        'image_url' => true,
        'is_free' => false,
        'groups' => false,
        'prices' => false,
        'virtual_prices' => false,
        'media_list' => false,
        'order' => false,
        'is_enabled' => false,
        'is_show_in_store' => false,
        'regions' => false,
        'content' => false,
        'limits' => true,
        'periods' => false,
        'custom_attributes' => false,
        'total_content_price' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'item_id' => 'item_id',
        'sku' => 'sku',
        'name' => 'name',
        'attributes' => 'attributes',
        'type' => 'type',
        'bundle_type' => 'bundle_type',
        'description' => 'description',
        'long_description' => 'long_description',
        'image_url' => 'image_url',
        'is_free' => 'is_free',
        'groups' => 'groups',
        'prices' => 'prices',
        'virtual_prices' => 'virtual_prices',
        'media_list' => 'media_list',
        'order' => 'order',
        'is_enabled' => 'is_enabled',
        'is_show_in_store' => 'is_show_in_store',
        'regions' => 'regions',
        'content' => 'content',
        'limits' => 'limits',
        'periods' => 'periods',
        'custom_attributes' => 'custom_attributes',
        'total_content_price' => 'total_content_price'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'item_id' => 'setItemId',
        'sku' => 'setSku',
        'name' => 'setName',
        'attributes' => 'setAttributes',
        'type' => 'setType',
        'bundle_type' => 'setBundleType',
        'description' => 'setDescription',
        'long_description' => 'setLongDescription',
        'image_url' => 'setImageUrl',
        'is_free' => 'setIsFree',
        'groups' => 'setGroups',
        'prices' => 'setPrices',
        'virtual_prices' => 'setVirtualPrices',
        'media_list' => 'setMediaList',
        'order' => 'setOrder',
        'is_enabled' => 'setIsEnabled',
        'is_show_in_store' => 'setIsShowInStore',
        'regions' => 'setRegions',
        'content' => 'setContent',
        'limits' => 'setLimits',
        'periods' => 'setPeriods',
        'custom_attributes' => 'setCustomAttributes',
        'total_content_price' => 'setTotalContentPrice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'item_id' => 'getItemId',
        'sku' => 'getSku',
        'name' => 'getName',
        'attributes' => 'getAttributes',
        'type' => 'getType',
        'bundle_type' => 'getBundleType',
        'description' => 'getDescription',
        'long_description' => 'getLongDescription',
        'image_url' => 'getImageUrl',
        'is_free' => 'getIsFree',
        'groups' => 'getGroups',
        'prices' => 'getPrices',
        'virtual_prices' => 'getVirtualPrices',
        'media_list' => 'getMediaList',
        'order' => 'getOrder',
        'is_enabled' => 'getIsEnabled',
        'is_show_in_store' => 'getIsShowInStore',
        'regions' => 'getRegions',
        'content' => 'getContent',
        'limits' => 'getLimits',
        'periods' => 'getPeriods',
        'custom_attributes' => 'getCustomAttributes',
        'total_content_price' => 'getTotalContentPrice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('item_id', $data ?? [], null);
        $this->setIfExists('sku', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('attributes', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('bundle_type', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('long_description', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('is_free', $data ?? [], false);
        $this->setIfExists('groups', $data ?? [], null);
        $this->setIfExists('prices', $data ?? [], null);
        $this->setIfExists('virtual_prices', $data ?? [], null);
        $this->setIfExists('media_list', $data ?? [], null);
        $this->setIfExists('order', $data ?? [], 1);
        $this->setIfExists('is_enabled', $data ?? [], true);
        $this->setIfExists('is_show_in_store', $data ?? [], false);
        $this->setIfExists('regions', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('limits', $data ?? [], null);
        $this->setIfExists('periods', $data ?? [], null);
        $this->setIfExists('custom_attributes', $data ?? [], null);
        $this->setIfExists('total_content_price', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['sku']) && (mb_strlen($this->container['sku']) > 255)) {
            $invalidProperties[] = "invalid value for 'sku', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['sku']) && (mb_strlen($this->container['sku']) < 1)) {
            $invalidProperties[] = "invalid value for 'sku', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['sku']) && !preg_match("/^[a-zA-Z0-9_\\-–.]*$/", $this->container['sku'])) {
            $invalidProperties[] = "invalid value for 'sku', must be conform to the pattern /^[a-zA-Z0-9_\\-–.]*$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets item_id
     *
     * @return int|null
     */
    public function getItemId()
    {
        return $this->container['item_id'];
    }

    /**
     * Sets item_id
     *
     * @param int|null $item_id Internal unique item ID.
     *
     * @return self
     */
    public function setItemId($item_id)
    {
        if (is_null($item_id)) {
            throw new \InvalidArgumentException('non-nullable item_id cannot be null');
        }


        $this->container['item_id'] = $item_id;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string|null
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string|null $sku Unique item ID. The SKU may contain only lowercase and uppercase Latin alphanumeric characters, periods, dashes, and underscores.
     *
     * @return self
     */
    public function setSku($sku)
    {
        if (is_null($sku)) {
            throw new \InvalidArgumentException('non-nullable sku cannot be null');
        }
        if ((mb_strlen($sku) > 255)) {
            throw new \InvalidArgumentException('invalid length for $sku when calling BundlesAdminBundleResponse., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($sku) < 1)) {
            throw new \InvalidArgumentException('invalid length for $sku when calling BundlesAdminBundleResponse., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[a-zA-Z0-9_\\-–.]*$/", ObjectSerializer::toString($sku)))) {
            throw new \InvalidArgumentException("invalid value for \$sku when calling BundlesAdminBundleResponse., must conform to the pattern /^[a-zA-Z0-9_\\-–.]*$/.");
        }

        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets name
     *
     * @return \OpenAPI\Client\Model\NameLocalizationObject|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param \OpenAPI\Client\Model\NameLocalizationObject|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets attributes
     *
     * @return \OpenAPI\Client\Model\Attribute[]|null
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param \OpenAPI\Client\Model\Attribute[]|null $attributes List of attributes.
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type Type of item.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets bundle_type
     *
     * @return \OpenAPI\Client\Model\BundleType|null
     */
    public function getBundleType()
    {
        return $this->container['bundle_type'];
    }

    /**
     * Sets bundle_type
     *
     * @param \OpenAPI\Client\Model\BundleType|null $bundle_type bundle_type
     *
     * @return self
     */
    public function setBundleType($bundle_type)
    {
        if (is_null($bundle_type)) {
            throw new \InvalidArgumentException('non-nullable bundle_type cannot be null');
        }
        $this->container['bundle_type'] = $bundle_type;

        return $this;
    }

    /**
     * Gets description
     *
     * @return \OpenAPI\Client\Model\DescriptionLocalizationObject|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param \OpenAPI\Client\Model\DescriptionLocalizationObject|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets long_description
     *
     * @return \OpenAPI\Client\Model\LongDescriptionLocalizationObject|null
     */
    public function getLongDescription()
    {
        return $this->container['long_description'];
    }

    /**
     * Sets long_description
     *
     * @param \OpenAPI\Client\Model\LongDescriptionLocalizationObject|null $long_description long_description
     *
     * @return self
     */
    public function setLongDescription($long_description)
    {
        if (is_null($long_description)) {
            array_push($this->openAPINullablesSetToNull, 'long_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('long_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['long_description'] = $long_description;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string|null
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url Image URL.
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            array_push($this->openAPINullablesSetToNull, 'image_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets is_free
     *
     * @return bool|null
     */
    public function getIsFree()
    {
        return $this->container['is_free'];
    }

    /**
     * Sets is_free
     *
     * @param bool|null $is_free If `true`, the item is free.
     *
     * @return self
     */
    public function setIsFree($is_free)
    {
        if (is_null($is_free)) {
            throw new \InvalidArgumentException('non-nullable is_free cannot be null');
        }
        $this->container['is_free'] = $is_free;

        return $this;
    }

    /**
     * Gets groups
     *
     * @return \OpenAPI\Client\Model\BundlesGroupsResponseInner[]|null
     */
    public function getGroups()
    {
        return $this->container['groups'];
    }

    /**
     * Sets groups
     *
     * @param \OpenAPI\Client\Model\BundlesGroupsResponseInner[]|null $groups Groups the item belongs to.
     *
     * @return self
     */
    public function setGroups($groups)
    {
        if (is_null($groups)) {
            throw new \InvalidArgumentException('non-nullable groups cannot be null');
        }
        $this->container['groups'] = $groups;

        return $this;
    }

    /**
     * Gets prices
     *
     * @return \OpenAPI\Client\Model\BundlesPricesInner[]|null
     */
    public function getPrices()
    {
        return $this->container['prices'];
    }

    /**
     * Sets prices
     *
     * @param \OpenAPI\Client\Model\BundlesPricesInner[]|null $prices Prices in real currencies.
     *
     * @return self
     */
    public function setPrices($prices)
    {
        if (is_null($prices)) {
            throw new \InvalidArgumentException('non-nullable prices cannot be null');
        }
        $this->container['prices'] = $prices;

        return $this;
    }

    /**
     * Gets virtual_prices
     *
     * @return \OpenAPI\Client\Model\BundlesAdminResponseVirtualPrice[]|null
     */
    public function getVirtualPrices()
    {
        return $this->container['virtual_prices'];
    }

    /**
     * Sets virtual_prices
     *
     * @param \OpenAPI\Client\Model\BundlesAdminResponseVirtualPrice[]|null $virtual_prices virtual_prices
     *
     * @return self
     */
    public function setVirtualPrices($virtual_prices)
    {
        if (is_null($virtual_prices)) {
            throw new \InvalidArgumentException('non-nullable virtual_prices cannot be null');
        }
        $this->container['virtual_prices'] = $virtual_prices;

        return $this;
    }

    /**
     * Gets media_list
     *
     * @return ArrayString|null
     */
    public function getMediaList()
    {
        return $this->container['media_list'];
    }

    /**
     * Sets media_list
     *
     * @param ArrayString|null $media_list media_list
     *
     * @return self
     */
    public function setMediaList($media_list)
    {
        if (is_null($media_list)) {
            throw new \InvalidArgumentException('non-nullable media_list cannot be null');
        }
        $this->container['media_list'] = $media_list;

        return $this;
    }

    /**
     * Gets order
     *
     * @return int|null
     */
    public function getOrder()
    {
        return $this->container['order'];
    }

    /**
     * Sets order
     *
     * @param int|null $order Bundle's order priority in the list.
     *
     * @return self
     */
    public function setOrder($order)
    {
        if (is_null($order)) {
            throw new \InvalidArgumentException('non-nullable order cannot be null');
        }
        $this->container['order'] = $order;

        return $this;
    }

    /**
     * Gets is_enabled
     *
     * @return bool|null
     */
    public function getIsEnabled()
    {
        return $this->container['is_enabled'];
    }

    /**
     * Sets is_enabled
     *
     * @param bool|null $is_enabled If disabled, the item can't be found and purchased.
     *
     * @return self
     */
    public function setIsEnabled($is_enabled)
    {
        if (is_null($is_enabled)) {
            throw new \InvalidArgumentException('non-nullable is_enabled cannot be null');
        }
        $this->container['is_enabled'] = $is_enabled;

        return $this;
    }

    /**
     * Gets is_show_in_store
     *
     * @return bool|null
     */
    public function getIsShowInStore()
    {
        return $this->container['is_show_in_store'];
    }

    /**
     * Sets is_show_in_store
     *
     * @param bool|null $is_show_in_store Item is available for purchase.
     *
     * @return self
     */
    public function setIsShowInStore($is_show_in_store)
    {
        if (is_null($is_show_in_store)) {
            throw new \InvalidArgumentException('non-nullable is_show_in_store cannot be null');
        }
        $this->container['is_show_in_store'] = $is_show_in_store;

        return $this;
    }

    /**
     * Gets regions
     *
     * @return \OpenAPI\Client\Model\BundlesAdminRegionsInner[]|null
     */
    public function getRegions()
    {
        return $this->container['regions'];
    }

    /**
     * Sets regions
     *
     * @param \OpenAPI\Client\Model\BundlesAdminRegionsInner[]|null $regions regions
     *
     * @return self
     */
    public function setRegions($regions)
    {
        if (is_null($regions)) {
            throw new \InvalidArgumentException('non-nullable regions cannot be null');
        }
        $this->container['regions'] = $regions;

        return $this;
    }

    /**
     * Gets content
     *
     * @return \OpenAPI\Client\Model\BundlesAdminContentResponse[]|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param \OpenAPI\Client\Model\BundlesAdminContentResponse[]|null $content content
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets limits
     *
     * @return \OpenAPI\Client\Model\ItemLimitResponse|null
     */
    public function getLimits()
    {
        return $this->container['limits'];
    }

    /**
     * Sets limits
     *
     * @param \OpenAPI\Client\Model\ItemLimitResponse|null $limits limits
     *
     * @return self
     */
    public function setLimits($limits)
    {
        if (is_null($limits)) {
            array_push($this->openAPINullablesSetToNull, 'limits');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limits', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limits'] = $limits;

        return $this;
    }

    /**
     * Gets periods
     *
     * @return \OpenAPI\Client\Model\ItemPeriodsResponseInner[]|null
     */
    public function getPeriods()
    {
        return $this->container['periods'];
    }

    /**
     * Sets periods
     *
     * @param \OpenAPI\Client\Model\ItemPeriodsResponseInner[]|null $periods Item sales period.
     *
     * @return self
     */
    public function setPeriods($periods)
    {
        if (is_null($periods)) {
            throw new \InvalidArgumentException('non-nullable periods cannot be null');
        }
        $this->container['periods'] = $periods;

        return $this;
    }

    /**
     * Gets custom_attributes
     *
     * @return object|null
     */
    public function getCustomAttributes()
    {
        return $this->container['custom_attributes'];
    }

    /**
     * Sets custom_attributes
     *
     * @param object|null $custom_attributes A JSON object containing item attributes and values.
     *
     * @return self
     */
    public function setCustomAttributes($custom_attributes)
    {
        if (is_null($custom_attributes)) {
            throw new \InvalidArgumentException('non-nullable custom_attributes cannot be null');
        }
        $this->container['custom_attributes'] = $custom_attributes;

        return $this;
    }

    /**
     * Gets total_content_price
     *
     * @return \OpenAPI\Client\Model\BundlesTotalContentPrice|null
     */
    public function getTotalContentPrice()
    {
        return $this->container['total_content_price'];
    }

    /**
     * Sets total_content_price
     *
     * @param \OpenAPI\Client\Model\BundlesTotalContentPrice|null $total_content_price total_content_price
     *
     * @return self
     */
    public function setTotalContentPrice($total_content_price)
    {
        if (is_null($total_content_price)) {
            array_push($this->openAPINullablesSetToNull, 'total_content_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_content_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_content_price'] = $total_content_price;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


