<?php
/**
 * PromotionsCouponsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shop Builder API
 *
 * # Overview  * **Version:** 2.0.0 * **Servers**: `https://store.xsolla.com/api` * **[Contact Us by Email](mailto:integration@xsolla.com)** * **Contact URL:** https://xsolla.com/ * **Required TLS version:** 1.2  Shop Builder API provides a third-party solution for implementing the server side for your store interface. Use the endpoints to manage in-game items, in-game currencies, cart, player inventory, promotions, game library, etc.  # Download API definition  You can download the API definition in two formats: - [YAML](https://api.redocly.com/registry/bundle/xsolla/store-en/v1/openapi.yaml) - [JSON](https://api.redocly.com/registry/bundle/xsolla/store-en/v1/openapi.json)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PromotionsCouponsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PromotionsCouponsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activateCoupon
     *
     * Activate coupon promotion.
     *
     */
    public function testActivateCoupon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addCouponUserPromotionLimit
     *
     * Increase coupon limit for specified user.
     *
     */
    public function testAddCouponUserPromotionLimit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminCreateCoupon
     *
     * Create coupon promotion.
     *
     */
    public function testAdminCreateCoupon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCouponCode
     *
     * Create coupon code.
     *
     */
    public function testCreateCouponCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deactivateCoupon
     *
     * Deactivate coupon promotion.
     *
     */
    public function testDeactivateCoupon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCouponPromotion
     *
     * Delete coupon promotion.
     *
     */
    public function testDeleteCouponPromotion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateCouponCodes
     *
     * Generate coupon codes.
     *
     */
    public function testGenerateCouponCodes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCoupon
     *
     * Get coupon promotion.
     *
     */
    public function testGetCoupon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCouponCodeLimit
     *
     * Get unique coupon code limits.
     *
     */
    public function testGetCouponCodeLimit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCouponCodes
     *
     * Get coupon codes.
     *
     */
    public function testGetCouponCodes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCouponRewardsByCode
     *
     * Get coupon rewards.
     *
     */
    public function testGetCouponRewardsByCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCouponUserLimit
     *
     * Get coupon limit for specified user.
     *
     */
    public function testGetCouponUserLimit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCoupons
     *
     * Get list of coupon promotions.
     *
     */
    public function testGetCoupons()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redeemCoupon
     *
     * Redeem coupon code.
     *
     */
    public function testRedeemCoupon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeCouponUserPromotionLimit
     *
     * Decrease coupon limit for specified user.
     *
     */
    public function testRemoveCouponUserPromotionLimit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setCouponUserPromotionLimit
     *
     * Set coupon limit for specified user.
     *
     */
    public function testSetCouponUserPromotionLimit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCouponPromotion
     *
     * Update coupon promotion.
     *
     */
    public function testUpdateCouponPromotion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
